version: "3.9"

services:
  client:
    container_name: client-container
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - server
    networks:
      - whatsapp_network
    ports:
      - "3000:3000"

  db:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_DATABASE: whatsapp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - whatsapp_network
    ports:
      - "3306:3306"

  server:
    container_name: server-container
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - db
    networks:
      - whatsapp_network
    ports:
      - "5000:5000"

networks:
  whatsapp_network:
