version: "3.9"

services:
  client:
    container_name: client-container
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - server
    env_file:
      - ./client/.env.local
    volumes:
      - /usr/src/app/client/node_modules
      - /usr/src/app/client/.next
      - ./client/src:/usr/src/app/client/src
    networks:
      - whatsapp_network
    ports:
      - "3000:3000"

  db:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_DATABASE: whatsapp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - whatsapp_network
    ports:
      - "3306:3306"

  server:
    container_name: server-container
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - db
    env_file:
      - ./server/.env
    volumes:
      - /usr/src/app/server/node_modules
      - ./server:/usr/src/app/server
    networks:
      - whatsapp_network
    ports:
      - "5000:5000"

networks:
  whatsapp_network:
